ignore:
  - "docs"
  - "generated-docs"
  - "website"
  - "**/OrphanCatsMessages.scala"
  - "**/OrphanCirceMessages.scala"
  - "**/OrphanSprayJsonMessages.scala"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
